[package]
name = "reference-kbc"
version = "0.1.0"
edition = "2021"
authors = ["Stefano Garzarella <sgarzare@redhat.com>"]

[features]
default = [ "std" ]
alloc = [ "hex/alloc", "kbs-types/alloc", "serde/alloc", "serde_json/alloc" ]
std = [ "hex/std", "kbs-types/std", "serde/std", "serde_json/std" ]

[dependencies]
anyhow = { version = "1.0.75", default-features = false }
hex = { version = "0.4", default-features = false }
#kbs-types = { version = "0.5.0", default-features = false }
kbs-types = { git = "https://github.com/virtee/kbs-types", default-features = false, features = ["tee-snp"] }
num-bigint = { version = "0.8", default-features = false, package = "num-bigint-dig" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false }

[dev-dependencies]
env_logger = "0.10.0"
log = "0.4.20"
rand = "0.8.5"
reqwest = { version = "0.11.22", features = ["json", "blocking", "cookies"] }
rsa = "0.9.3"
sha2 = "0.10.8"
sev = { version = "2.0", default-features = false, features = ["snp"] }
